#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""崩溃解析核心：按平台/thread 分块并组装 CrashAnalysisResult。"""

from __future__ import annotations

import logging
from dataclasses import replace
from typing import List, Optional

from tools.crash_parser.android import _android_stack_sample_hint
from tools.crash_parser.abort_message import thread_type_from_name
from tools.crash_parser.format_detect import detect_os_type
from tools.crash_parser.log_sections import detect_raw_log_sections, extract_build_ids
from tools.crash_parser.meta import extract_crash_info, extract_meta_info
from tools.crash_parser.platform_threads import (
    apply_android_thread_metadata,
    parse_threads_android_harmony_tid,
    parse_threads_ios,
    parse_threads_single_block,
)
from tools.crash_parser.register_analyzer import (
    build_registers_section,
    enrich_registers_from_backtrace,
)
from tools.crash_parser.types import (
    CrashAnalysisResult,
    CrashInfo,
    CrashParseOptions,
    ThreadStack,
    _maybe_filter_threads_by_library_dir,
)

logger = logging.getLogger(__name__)


def parse_crash_core(
    content: str,
    os_type: Optional[str] = None,
    debug: bool = False,
    *,
    options: Optional[CrashParseOptions] = None,
) -> CrashAnalysisResult:
    """核心解析逻辑：按线程分组堆栈 + 提取 crash/meta 信息"""
    opts = options if options is not None else CrashParseOptions()
    if os_type is None:
        os_type = detect_os_type(content)

    crash_seg_req = max(1, int(opts.crash_segment_index))
    threads: List[ThreadStack] = []
    thread_count_total_val: Optional[int] = None
    crash_backtrace_count = 1
    total_frames = 0

    tid_result = parse_threads_android_harmony_tid(content, os_type, debug, opts)
    if tid_result is not None:
        threads, thread_count_total_val, crash_backtrace_count, total_frames = tid_result
    elif os_type == "ios":
        threads, thread_count_total_val, crash_backtrace_count, total_frames = parse_threads_ios(
            content, debug, opts
        )
    else:
        threads, thread_count_total_val, crash_backtrace_count, total_frames = parse_threads_single_block(
            content, os_type, debug, opts
        )

    if os_type == "android":
        threads = apply_android_thread_metadata(content, threads)

    threads, removed_by_lib_filter, lib_filter_applied = _maybe_filter_threads_by_library_dir(
        threads, os_type, opts,
    )
    total_frames = sum(len(t.frames) for t in threads)

    crash_info = extract_crash_info(content)
    crash_info = _align_thread_type_with_crash_thread(crash_info, threads)
    meta_info = extract_meta_info(content)

    # 推断性分析已迁移到 02b/04a_crash_diagnosis 模块
    # signal_semantics 和 address_pattern 不再写入 01

    build_ids = extract_build_ids(content)
    registers, reg_module_bases = build_registers_section(
        content, crash_info.crash_address
    )
    registers, bt_bases = enrich_registers_from_backtrace(registers, threads)
    # 合并寄存器命中 so 的装载基址（不全量 maps）
    merged_bases = dict(meta_info.module_base_addresses or {})
    for mod, base in {**(reg_module_bases or {}), **(bt_bases or {})}.items():
        if mod and base and mod not in merged_bases:
            merged_bases[mod] = base

    meta_info = replace(
        meta_info,
        thread_count_total=thread_count_total_val,
        thread_count_extracted=len(threads),
        library_dir_frame_filter_applied=lib_filter_applied if lib_filter_applied else None,
        frames_removed_by_library_dir_filter=(
            removed_by_lib_filter if lib_filter_applied else None
        ),
        build_ids=build_ids,
        module_base_addresses=merged_bases or None,
    )

    parse_status = "ok"
    content_lower = content.lower()
    header_markers = [
        "generated by",
        "device info:",
        "build info:",
        "fingerprint:",
        "reason:",
        "exception type:",
        "binary images:",
        "deadlock",
        "crashdoctor",
        "freeze type:",
        "freeze interval:",
        "卡顿",
        "fatal signal",
        "cmdline:",
        "fault addr",
        "signal ",
    ]
    has_header_hint = any(m in content_lower for m in header_markers)
    if _android_stack_sample_hint(content):
        has_header_hint = True

    has_threads = bool(threads)
    has_frames = total_frames > 0
    if has_frames and has_threads and not has_header_hint:
        parse_status = "partial_log"
    if not has_frames:
        parse_status = "error"

    raw_content = content if opts.save_raw_content else ""

    raw_log_sections = detect_raw_log_sections(content) or None

    return CrashAnalysisResult(
        crash_info=crash_info,
        meta_info=meta_info,
        threads=threads,
        raw_content=raw_content,
        registers=registers,
        crash_backtrace_sum_count=crash_backtrace_count,
        crash_backtrace_index_set=crash_seg_req,
        raw_log_sections=raw_log_sections,
        parse_status=parse_status,
    )


def _align_thread_type_with_crash_thread(
    crash_info: CrashInfo,
    threads: List[ThreadStack],
) -> CrashInfo:
    """用崩溃线程名/主线程标记覆盖默认 thread_type=main。"""
    crash = next((item for item in threads if item.is_crash_thread), None)
    if crash is None and threads:
        crash = threads[0]
    if crash is None:
        return crash_info
    if crash.is_main_thread is True:
        thread_type = "main"
    elif crash.is_main_thread is False:
        thread_type = "background"
    else:
        thread_type = thread_type_from_name(crash.name)
    if thread_type == crash_info.thread_type:
        return crash_info
    return replace(crash_info, thread_type=thread_type)
