#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""崩溃解析核心：按平台/thread 分块并组装 CrashAnalysisResult。"""

from __future__ import annotations

import logging
from dataclasses import replace
from typing import List, Optional

from tools.crash_parser.android import _android_stack_sample_hint
from tools.crash_parser.format_detect import detect_os_type
from tools.crash_parser.meta import extract_crash_info, extract_meta_info
from tools.crash_parser.platform_threads import (
    apply_android_thread_metadata,
    parse_threads_android_harmony_tid,
    parse_threads_ios,
    parse_threads_single_block,
)
from tools.crash_parser.types import (
    CrashAnalysisResult,
    CrashParseOptions,
    ThreadStack,
    _maybe_filter_threads_by_library_dir,
)

logger = logging.getLogger(__name__)


def parse_crash_core(
    content: str,
    os_type: Optional[str] = None,
    debug: bool = False,
    *,
    options: Optional[CrashParseOptions] = None,
) -> CrashAnalysisResult:
    """核心解析逻辑：按线程分组堆栈 + 提取 crash/meta 信息"""
    opts = options if options is not None else CrashParseOptions()
    if os_type is None:
        os_type = detect_os_type(content)

    crash_seg_req = max(1, int(opts.crash_segment_index))
    threads: List[ThreadStack] = []
    thread_count_total_val: Optional[int] = None
    crash_backtrace_count = 1
    total_frames = 0

    tid_result = parse_threads_android_harmony_tid(content, os_type, debug, opts)
    if tid_result is not None:
        threads, thread_count_total_val, crash_backtrace_count, total_frames = tid_result
    elif os_type == "ios":
        threads, thread_count_total_val, crash_backtrace_count, total_frames = parse_threads_ios(
            content, debug, opts
        )
    else:
        threads, thread_count_total_val, crash_backtrace_count, total_frames = parse_threads_single_block(
            content, os_type, debug, opts
        )

    if os_type == "android":
        threads = apply_android_thread_metadata(content, threads)

    threads, removed_by_lib_filter, lib_filter_applied = _maybe_filter_threads_by_library_dir(
        threads, os_type, opts,
    )
    total_frames = sum(len(t.frames) for t in threads)

    crash_info = extract_crash_info(content)
    meta_info = extract_meta_info(content)
    meta_info = replace(
        meta_info,
        thread_count_total=thread_count_total_val,
        thread_count_extracted=len(threads),
        library_dir_frame_filter_applied=lib_filter_applied if lib_filter_applied else None,
        frames_removed_by_library_dir_filter=(
            removed_by_lib_filter if lib_filter_applied else None
        ),
    )

    parse_status = "ok"
    content_lower = content.lower()
    header_markers = [
        "generated by",
        "device info:",
        "build info:",
        "fingerprint:",
        "reason:",
        "exception type:",
        "binary images:",
        "deadlock",
        "crashdoctor",
        "freeze type:",
        "freeze interval:",
        "卡顿",
        "fatal signal",
        "cmdline:",
    ]
    has_header_hint = any(m in content_lower for m in header_markers)
    if _android_stack_sample_hint(content):
        has_header_hint = True

    has_threads = bool(threads)
    has_frames = total_frames > 0
    if has_frames and has_threads and not has_header_hint:
        parse_status = "partial_log"
    if not has_frames:
        parse_status = "error"

    raw_content = content if opts.save_raw_content else ""

    return CrashAnalysisResult(
        threads=threads,
        crash_info=crash_info,
        meta_info=meta_info,
        raw_content=raw_content,
        parse_status=parse_status,
        crash_backtrace_sum_count=crash_backtrace_count,
        crash_backtrace_index_set=crash_seg_req,
    )
