#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Skill 模板生成器。
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


def _skill_name(raw: str) -> str:
    cleaned = []
    for ch in str(raw).strip().lower():
        if ch.isalnum() or ch in {"-", "_"}:
            cleaned.append(ch)
        elif ch.isspace():
            cleaned.append("-")
    name = "".join(cleaned).strip("-_")
    return name or "skill"


def render_skill_scaffold(skill_name: str, skill_type: str = "prompt") -> Dict[str, str]:
    """生成一个可直接落盘的 skill 模板。"""
    command_name = _skill_name(skill_name)
    display_name = skill_name.strip() or command_name
    skill_type = (skill_type or "prompt").strip().lower()
    files: Dict[str, str] = {}

    if skill_type == "prompt":
        files["SKILL.md"] = f"""---
name: {display_name}
description: Describe what this skill does and when to use it.
---

## What this skill does

Write short, actionable instructions here.

## Supporting context

- Add references, checklists, or examples in supporting files.
- Keep this file concise so it stays cheap to load.
"""
    else:
        files["SKILL.md"] = f"""---
name: {display_name}
description: Describe what this skill does and when to use it.
disable-model-invocation: true
---

## Instructions

Write the workflow or task instructions here.
"""

    manifest: Dict[str, Any] = {
        "id": command_name,
        "name": display_name,
        "command_name": command_name,
        "version": "0.1.0",
        "type": skill_type,
        "description": f"{display_name} skill",
        "entrypoint": "prompt" if skill_type == "prompt" else f"workflow:{command_name}",
        "exports": [],
        "dependencies": [],
        "tags": ["stability-analysis-agent", "skill"],
        "metadata": {
            "generated": True,
            "skill_kind": skill_type,
        },
    }
    if skill_type in {"workflow", "tool", "plugin"}:
        manifest["exports"] = [
            {
                "kind": "module",
                "ref": "skill_module:register_all",
                "name": command_name,
                "priority": "CUSTOM",
                "force_override": False,
                "enabled": True,
                "params": {},
                "metadata": {
                    "note": "Replace with your real module path or register function.",
                },
            }
        ]

    files["skill.json"] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    files["README.md"] = f"""# {display_name}

This skill was generated by `sa-agent skill init`.

- Command name: `{command_name}`
- Type: `{skill_type}`
- Entry point: `{manifest["entrypoint"]}`

For Claude-compatible usage, keep `SKILL.md` as the main entry file.
"""
    return files


def write_skill_scaffold(target_dir: Path, skill_name: str, skill_type: str = "prompt", overwrite: bool = False) -> List[Path]:
    """把 skill 模板写入目标目录。"""
    target_dir = target_dir.expanduser().resolve()
    if target_dir.exists() and not overwrite:
        raise FileExistsError(f"目标目录已存在: {target_dir}")
    target_dir.mkdir(parents=True, exist_ok=True)

    written: List[Path] = []
    for rel, content in render_skill_scaffold(skill_name, skill_type).items():
        path = target_dir / rel
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written

